### ISSUE TITLE
Lack of undervoltage calculation

### ISSUE THREAD

**Issue by danho96** [gorniak/VoltDiv#1]
Looking for 1V1 output voltage with 0.6V reverence, the closest resutl was ~1.13V and it was increasing. There were no values <1.1V as well as the perfect solution Rtop=10k, Rbot=12k.

I found the proper divider by changing the target voltage to 1V.

**Comment by gorniak** [comment]
Thank you for detecting this issue. The error is fixed in commit [0341c08](https://github.com/gorniak/VoltDiv/commit/0341c0868be804e3ea13e06a64c67fa7ea8df5e9).
