### ISSUE TITLE
Fake Error indicatior

### ISSUE THREAD

**Issue by danho96** [gorniak/VoltDiv#2]
Looking for Uout=1.8V, Uref=0.6V I got many perfect results (as expected), however in such cases I received ERR[V]=-2.22044604925031E-16.

**Comment by gorniak** [comment]
Thank you for detecting this issue. The error is fixed in commit [0341c08](https://github.com/gorniak/VoltDiv/commit/0341c0868be804e3ea13e06a64c67fa7ea8df5e9).
